import { Peptide } from "./types";

export const PEPTIDE_DATABASE: Peptide[] = [
  {
    id: "bpc-157",
    name: "BPC-157",
    fullName: "Body Protecting Compound 157",
    category: "healing",
    class: "Penta-decapeptide (15 amino acids) derived from gastric juice",
    description: "Highly stable peptide renowned for acceleration of systemic soft tissue healing. Studies show substantial efficacy in healing tendons, ligaments, muscle tissue, skin grafts, and inflammatory gut conditions (gastric ulcers, Crohn's, IBS). It also exerts strong angiogenic (blood vessel building) and neuroprotective effects.",
    halfLife: "Approx. 4 hours",
    molecularWeight: "1419.5 g/mol",
    sequence: "Gly-Glu-Pro-Pro-Pro-Gly-Lys-Pro-Ala-Asp-Asp-Ala-Gly-Leu-Val",
    standardReconstitution: "2mL or 3mL Bacteriostatic Water per 5mg vial",
    dosageRange: "250 - 500 mcg twice daily (subcutaneous or intramuscular near injury site)",
    protocols: "Usually administered for 4 - 8 weeks, followed by a 2-week rest period. Commonly stacked with TB-500 for rapid synergistic injury recovery."
  },
  {
    id: "tb-500",
    name: "TB-500",
    fullName: "Thymosin Beta-4 (Synthetic)",
    category: "healing",
    class: "Synthetic fraction of Thymosin Beta-4 peptide (43 amino acids)",
    description: "Promotes cell migration, blood vessel formation (angiogenesis), wound healing, and cellular tissue regeneration. Unlike BPC-157, TB-500 has high systemic mobility, diffusing rapidly throughout bodily tissues. It excels in improving range of motion, reducing chronic muscle and joint inflammation, and stimulating hair growth.",
    halfLife: "Approx. 7 - 10 days",
    molecularWeight: "4963.5 g/mol",
    sequence: "Ac-Ser-Asp-Lys-Pro-Asp-Met-Ala-Glu-Ile-Glu-Lys-Phe-Asp-Lys-Ser-Lys-Leu-Lys-Lys-Thr-Glu-Thr-Gln-Glu-Lys-Asn-Pro-Leu-Pro-Ser-Lys-Glu-Thr-Ile-Glu-Gln-Glu-Lys-Gln-Ala-Gly-Glu-Ser-OH",
    standardReconstitution: "2mL Bacteriostatic Water per 5mg vial",
    dosageRange: "2.5 - 5.0 mg twice weekly (subcutaneous or intramuscular)",
    protocols: "Loading phase of 5mg per week (split into two 2.5mg doses) for 4 - 6 weeks, followed by a maintenance phase of 2.5mg per week for 4 - 8 weeks."
  },
  {
    id: "semaglutide",
    name: "Semaglutide",
    fullName: "Semaglutide (GLP-1 Receptor Agonist)",
    category: "weight",
    class: "Glucagon-Like Peptide-1 (GLP-1) receptor agonist",
    description: "Highly effective weight management peptide that mimics the human GLP-1 hormone. It slows gastric emptying (leading to prolonged satiety), reduces appetite and food cravings via central nervous system pathways, and enhances insulin secretion while suppressing inappropriate glucagon secretion.",
    halfLife: "Approx. 7 days (168 hours)",
    molecularWeight: "4113.6 g/mol",
    sequence: "H-His-Aib-Glu-Gly-Thr-Phe-Thr-Ser-Asp-Val-Ser-Ser-Tyr-Leu-Glu-Gly-Gln-Ala-Ala-Lys(AEEAc-AEEAc-γ-Glu-Otic)-Glu-Phe-Ile-Ala-Trp-Leu-Val-Arg-Gly-Arg-Gly-OH",
    standardReconstitution: "2mL or 3mL Bacteriostatic Water per 5mg vial",
    dosageRange: "0.25 mg to 2.4 mg once weekly (subcutaneous, starting low and titrating up)",
    protocols: "Titration schedule: 0.25mg/week for weeks 1-4, 0.5mg/week for weeks 5-8, 1.0mg/week for weeks 9-12, scaling up to a maximum therapeutic dose of 2.4mg if tolerated."
  },
  {
    id: "tirzepatide",
    name: "Tirzepatide",
    fullName: "Tirzepatide (GIP/GLP-1 Receptor Co-agonist)",
    category: "weight",
    class: "Dual GIP and GLP-1 receptor co-agonist",
    description: "Next-generation weight loss and glycemic control peptide. It is a single synthetic peptide that activates both the GLP-1 and the GIP (glucose-dependent insulinotropic polypeptide) receptor pathways. The dual action produces greater caloric restriction, adiposity reduction, and lipid profile improvements than GLP-1 agonists alone.",
    halfLife: "Approx. 5 days (120 hours)",
    molecularWeight: "4813.5 g/mol",
    standardReconstitution: "2mL Bacteriostatic Water per 10mg vial",
    dosageRange: "2.5 mg to 15.0 mg once weekly (subcutaneous)",
    protocols: "Start at 2.5mg once weekly for 4 weeks. Increase by 2.5mg increments every 4 weeks (e.g., 5mg, 7.5mg, 10mg, 12.5mg, up to 15mg max) based on research outcomes and tolerability."
  },
  {
    id: "cjc-1295-no-dac",
    name: "CJC-1295 (No-DAC)",
    fullName: "CJC-1295 No-DAC (Mod GRF 1-29)",
    category: "gh",
    class: "Growth Hormone Releasing Hormone (GHRH) analog",
    description: "A 29-amino acid synthetic analog of GHRH that stimulates the anterior pituitary to secrete natural Growth Hormone (GH). By omitting the Drug Affinity Complex (DAC), No-DAC produces natural pulsatile peaks of GH instead of a continuous elevated bleed, minimizing pituitary fatigue and maintaining normal homeostatic biorhythms.",
    halfLife: "Approx. 30 minutes",
    molecularWeight: "3367.9 g/mol",
    sequence: "Tyr-D-Ala-Asp-Ala-Ile-Phe-Thr-Gln-Ser-Tyr-Arg-Lys-Val-Leu-Ala-Gln-Leu-Ser-Ala-Arg-Lys-Leu-Leu-Gln-Asp-Ile-Leu-Ser-Arg-NH2",
    standardReconstitution: "2mL Bacteriostatic Water per 5mg vial",
    dosageRange: "100 - 150 mcg up to three times daily (subcutaneous on empty stomach)",
    protocols: "Typically administered 1-3 times daily (morning, post-workout, and before bed). Must be taken on a strict empty stomach (no food 2 hours prior, 30 mins after) to avoid insulin blunting. Almost always stacked with Ipamorelin."
  },
  {
    id: "ipamorelin",
    name: "Ipamorelin",
    fullName: "Ipamorelin (GH Secretagogue)",
    category: "gh",
    class: "Selective Growth Hormone Secretagogue Receptor (GHSR) agonist",
    description: "Highly selective pentapeptide that stimulates a pulse of Growth Hormone release. Unlike older GH secretagogues (like GHRP-2 or GHRP-6), Ipamorelin is extremely clean: it does not increase appetite, cortisol, prolactin, or aldosterone. It promotes lean muscle retention, fat oxidation, bone density, and improved deep sleep profiles.",
    halfLife: "Approx. 2 hours",
    molecularWeight: "711.9 g/mol",
    sequence: "Aib-His-D-2-Nal-D-Phe-Lys-NH2",
    standardReconstitution: "2mL Bacteriostatic Water per 5mg or 10mg vial",
    dosageRange: "100 - 300 mcg up to three times daily (subcutaneous on empty stomach)",
    protocols: "Administered 1-3 times daily, paired 1:1 with CJC-1295 No-DAC (e.g. 100mcg CJC + 100mcg Ipamorelin in a single syringe). Take before sleep or upon waking on an empty stomach. Cycle 12-16 weeks followed by a 4-week break."
  },
  {
    id: "ghk-cu",
    name: "GHK-Cu",
    fullName: "Copper Peptide GHK-Cu",
    category: "cosmetic",
    class: "Tripeptide-copper complex (Glycyl-L-Histidyl-L-Lysine)",
    description: "Highly potent tripeptide copper complex with remarkable regenerative and anti-aging properties. It stimulates collagen, elastin, and glycosaminoglycan synthesis in fibroblasts. It acts as an powerful antioxidant, promotes hair follicle growth, reduces deep wrinkles, and accelerates dermal tissue repair.",
    halfLife: "Approx. 1 hour (very short, but triggers long-lasting genetic upregulation)",
    molecularWeight: "340.4 g/mol (GHK free base)",
    standardReconstitution: "2mL to 3mL Bacteriostatic Water per 50mg vial",
    dosageRange: "2.0 - 5.0 mg daily (subcutaneous) OR 1% - 3% concentration in topical serums",
    protocols: "Subcutaneous research protocol: 2mg injected daily for 30 days, repeated 2-3 times per year. Often blended into customized anti-aging facial creams or scalp treatments."
  },
  {
    id: "melanotan-ii",
    name: "Melanotan II",
    fullName: "Melanotan II (MT-2)",
    category: "cosmetic",
    class: "Synthetic melanocortin receptor agonist",
    description: "A cyclic peptide analog of alpha-melanocyte stimulating hormone (α-MSH). It stimulates melanogenesis (melanin production) to produce skin tanning without requiring UV radiation exposure. Additionally, it crosses the blood-brain barrier to activate neural melanocortin receptors, reducing appetite and significantly enhancing libido/erectile function.",
    halfLife: "Approx. 1.5 hours",
    molecularWeight: "1024.2 g/mol",
    sequence: "Ac-Nle-asp-His-D-Phe-Arg-Trp-Lys-NH2 (Cyclized)",
    standardReconstitution: "2mL Bacteriostatic Water per 10mg vial",
    dosageRange: "250 - 500 mcg daily (subcutaneous, usually before bed to mitigate mild nausea)",
    protocols: "Loading phase: 250mcg daily, increasing to 500mcg if tolerated, until desired tan level is reached (typically 7-14 days). Maintenance phase: 500mcg 1-2 times weekly."
  },
  {
    id: "pt-141",
    name: "PT-141",
    fullName: "Bremelanotide (PT-141)",
    category: "other",
    class: "Melanocortin receptor agonist (active metabolite of MT-2)",
    description: "Developed from Melanotan II as a dedicated therapy for sexual dysfunction in both men and women. Unlike PDE5 inhibitors (e.g. Viagra) which act on the vascular system locally, PT-141 acts directly on melanocortin receptors in the central nervous system to drive desire, arousal, and erectile responses.",
    halfLife: "Approx. 2.7 hours",
    molecularWeight: "1024.2 g/mol",
    sequence: "Ac-Nle-Asp-His-D-Phe-Arg-Trp-Lys-OH (Cyclized)",
    standardReconstitution: "2mL Bacteriostatic Water per 10mg vial",
    dosageRange: "1.0 - 2.0 mg administered 4 - 6 hours prior to anticipated sexual activity (subcutaneous)",
    protocols: "On-demand administration only. Do not exceed 2mg within a 24-hour window, and limit use to at most 3 times per week to prevent melanocortin receptor downregulation."
  },
  {
    id: "epitalon",
    name: "Epitalon",
    fullName: "Epithalon (Epitalon)",
    category: "cognitive",
    class: "Tetrapeptide (4 amino acids) synthetic pineal gland extract",
    description: "An anti-aging peptide designed to activate the telomerase enzyme, leading to the elongation of telomeres (caps on chromosomes). Studies show it helps normalize pineal melatonin secretion, restores circadian sleep rhythms, boosts immune function, acts as a potent free radical scavenger, and extends overall lifespan in rodent models.",
    halfLife: "Approx. 1 hour",
    molecularWeight: "390.4 g/mol",
    sequence: "Ala-Glu-Asp-Gly",
    standardReconstitution: "2mL Bacteriostatic Water per 10mg vial",
    dosageRange: "5.0 - 10.0 mg injected daily (subcutaneous or intramuscular)",
    protocols: "Typical protocol: 10mg daily for 10 - 20 consecutive days (totaling 100mg to 200mg per course). This cycle is typically performed once or twice per year to encourage systemic longevity."
  }
];
